add invoker function
krakphp/fn pull request #11
Opened 2020-03-20 21:47 UTC by andres-ml

2020-03-21 21:32 UTC, ragboyjr commented
Hmm, i think this is already supported via the `method` fn. Unfortunately `method` isn't documented/tested, but we could add that test/documentation, and I think that should suffice.

What do you think?

2020-03-21 22:42 UTC, andres-ml commented
I actually saw it after the pull request but kind of dismissed it when I saw that the instance was taken as a 2nd parameter. I see now that its curried version `c\method` is effectively equal to `f\invoker`.
I kind of prefer `invoker` though; the curried versions of functions with variadic arguments feel kind of weird for me. Like, functions are data-last and in this case the data is the instance, but it goes before the method's arguments.

2020-03-21 22:50 UTC, ragboyjr commented
hmm, i honestly don't see a difference between:

invoker main implementation

```php
function invoker(string $method, ...$args) {
     return function($instance) use($method, $args) {
         return call_user_func_array([$instance, $method], $args);
     };
 }
```

and the curried method


```php
function method($name, ...$optionalArgs)
{
    return function ($data) use($name, $optionalArgs) {
        return $data->{$name}(...$optionalArgs);
    };
}
```

They have the same api and functionality, just the internal variable names are different.

```php
invoker('methodName', $arg1, $arg2)($obj);
method('methodName', $arg1, $arg2)($obj);
```

2020-03-21 22:52 UTC, ragboyjr commented
Unless i'm missing something, it doesn't seem to add value to have a new initially curried version of method. i'm not against an alias, but I'm also not convinced that invoker is a valid alias for what method is doing. Invoke implies invoking any type of callable, when in reality, it's ONLY invoking methods on objects. So the `method` naming that exists seems more appropriate.

I'd probably like to see the `method` function tested and therefore documented.

2020-03-21 23:04 UTC, andres-ml commented
Yes, I mentioned they're effectively the same. It's just that (at least personally) it makes more sense to me for the `($method, ...$args)` header to be the default one; i.e. part of the non-curried version of the function. I don't really see a situation where I'd use `f\method($m, $o)` when I can do `$m->o()`, but I could potentially see myself using `c\invoker($m)`.
As for the naming, I [based it on Ramda](https://ramdajs.com/docs/#invoker), as I usually do.

2020-03-21 23:11 UTC, ragboyjr commented
How would you feel about just making invoker an alias of curried method.

So the main definition is just

```php
function invoker(string $method, ...$args): callable {
  return \Krak\Fun\Curried\method($method, $args);
}
```

And we document method and invoker.

2020-03-24 20:59 UTC, ragboyjr requested changes

2020-03-24 20:59 UTC, ragboyjr commented on test/fn.spec.php
> +        });
Just need a small documentation update mentioning that this is an alias of curried method and then we are good to go.

2022-12-07 15:44 UTC, closed without merging